apiVersion: v1
kind: Service
metadata:
  name: project-demo
spec:
  selector:
    app: project-demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 8085
      nodePort: 31000
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-demo
  template:
    metadata:
      labels:
        app: project-demo
    spec:
      containers:
        - name: app
          image: pratimaa/project-demo
          ports:
            - containerPort: 8085